import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";
import { Manrope } from "next/font/google";
import { Toaster } from "react-hot-toast";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Rental Host",
  description: "Generated by Vordx",
};

// Define props type
type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
 <html lang="en"  >
      <body className={`${manrope.className} !overflow-x-hidden`}>
     <Toaster
          position="top-right"
          toastOptions={{
            duration: 4000,
            style: {
              background: "white",
              color: "black",
            },
            success: {
              duration: 3000,
            },
          }}
        />
        <main>{children}</main>
      </body>
    </html>
  );
}
