import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";
import { Manrope } from "next/font/google";

const manrope = Manrope({ subsets: ["latin"], variable: "--font-manrope" });

export const metadata: Metadata = {
  title: "Rental Host",
  description: "Generated by Vordx",
};

// Define props type
type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={` ${manrope.className} !overflow-x-hidden`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
